name: Deploy to github page

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: '26'
        cache: 'npm'

    - name: Build
      run: |
        npm i
        npm run build:github

    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: ./dist
      
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
